print('hola mundo')

def saluda(nombre):
    return 'hola {nombre}, Bienvenido al curso de Python.'.format(nombre=nombre)


print(saluda('Sebas'))
'''
print(saluda("Adriana Cristancho Pineda"))
print(saluda("Andrea Beatriz Amezquita Araque"))
print(saluda("Antony javier Estrada Araujo"))
print(saluda("Brayan Enrique Silva Marquez"))
print(saluda("Carlos Andres Florez Ochoa"))
print(saluda("Carolina Bastidas Rincon"))
print(saluda("Daniel Camilo Orejarena Vanegas"))
print(saluda("Deivert Farick Blanco Marin"))
print(saluda("Didier Alexander Luengas Reyes"))
print(saluda("Diego Fernando Albarracin Martinez"))
print(saluda("elkin ferney gomez reyes"))
print(saluda("Erick Mauricio Cepeda Ávila"))
print(saluda("fabian camilo alvarado sanabria"))
print(saluda("fabian enrique sanchez solano"))
print(saluda("Favian Enrique González Carreño"))
print(saluda("Harol jhioset Chinomes Caceres"))
print(saluda("Javier Alexis Garcia Luna"))
print(saluda("Jeison ferney Martínez duran"))
print(saluda("Jhoan Sebastian Velasco Velasquez"))
print(saluda("Jhonatan Alexis Ossa Osorio"))
print(saluda("José Luis Bautista González"))
print(saluda("Juan Diego Rojas Leon"))
print(saluda("Juan Fernando delgado Carvajal"))
print(saluda("JUAN KAMILO PICÓN GAMBOA"))
print(saluda("Juan Pablo Díaz Rubio"))
print(saluda("keiner johan marsiglia acuna"))
print(saluda("Luis Carlos Tobo Caceres"))
print(saluda("Luis mateo Betancour otero"))
print(saluda("Nelson Enrique Figueroa"))
print(saluda("Nixon James Son Galeano"))
print(saluda("ORLANDO LUIS ROZO GOMEZ"))
print(saluda("Óscar Javier Quiroga Hernández"))
print(saluda("Sara Lucía Acosta Gómez"))
print(saluda("wilinton ortega castilla"))
print(saluda("Willian Rico Pinzon"))
print(saluda("Yeiler Sneider Méndez Guevar,"))'''